version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
      - 50051:50051
    volumes:
      - .:/home/node/app
  
  grpc-test:
    image: gusaul/grpcox:latest
    ports: 
      - 6969:6969